### PR TITLE
Modify README.md to support Chinese

### PR DESCRIPTION
**Pull request by kwxmxb**
[README]: Modify README.md to support Chinese language display.

### CODE REVIEW

**Comment by jakepurple13** [comment]
@kwxmxb Are you continuing this at all?

**Comment by kwxmxb** [comment]
> @kwxmxb Are you continuing this at all?

I submit a request for open source project contribution, which can only be applied to the translation of a simple project introduction page

or APK installation package translation. You are all big guys, I am just a newbie, and I can only make a simple small contribution.

**Comment by kwxmxb** [comment]
I can usually only translate through translation software, so it may not be accurate. I may use AI to assist translation in the future.

**Review by jakepurple13 — APPROVED** [review]

**Comment by kwxmxb** [comment]
I would like to ask a question, that is, how to modify the code that wants to distinguish different languages?

Similar to this code case

[English](README.md) |[Chinese](README-zh.md)

If you add multiple, how to display them better? I would like to ask?

**Comment by kwxmxb** [comment]
> I would like to ask a question, that is, how to modify the code that wants to distinguish different languages?
> 
> Similar to this code case
> 
> [English](README.md) |[Chinese](README-zh.md)
> 
> If you add multiple, how to display them better? I would like to ask?

Because I think it is redundant to add English since the first option is in English by default, so I want to ask if it needs to be improved?

**Comment by jakepurple13** [comment]
The code would need to be improved to allow multiple languages. I haven't set it up for that since this has been a passion project. But go ahead and explore to add it!

**Comment by kwxmxb** [comment]
I like to use Android system now, and I prefer to use secondary distribution of Chinese software, but the only problem is that after distribution, the signature or verification value of its installation package will also change. Well, it should be in the unsigned state, will it change? I am not sure

**Comment by kwxmxb** [comment]
I only know Chinese for now. It may be difficult to translate other languages. However, I can use AI translation. At least there is a way to solve the problem.

**Comment by jakepurple13** [comment]
> I like to use Android system now, and I prefer to use secondary distribution of Chinese software, but the only problem is that after distribution, the signature or verification value of its installation package will also change. Well, it should be in the unsigned state, will it change? I am not sure

The ci/cd automatically signs it. So it should be fine, right?

**Comment by kwxmxb** [comment]
> > I like to use Android system now, and I prefer to use secondary distribution of Chinese software, but the only problem is that after distribution, the signature or verification value of its installation package will also change. Well, it should be in the unsigned state, will it change? I am not sure
> 
> The ci/cd automatically signs it. So it should be fine, right?

No, I use a mobile phone.
Well, there is a very useful tool developed by Russian brothers. Anyway, the signing and decompilation tools are combined, which is particularly convenient for signing.

I use MT Manager for translation, but I don’t want to translate everything. My translation process is to install the application and then translate according to the characters on the interface. Full translation is too cumbersome, and there are many characters, which is time-consuming.

**Comment by OSNewbie** [comment]
Optimize the language introduction page

Update the Chinese translation of the Code of Conduct

[https://github.com/OSNewbie/OtakuWorld-/blob/develop/README.md](url)

**Comment by jakepurple13** [comment]
I'll be adding more to the read me later today. So I'll look into this as I'm at it.

**Comment by OSNewbie** [comment]
> I'll be adding more to the read me later today. So I'll look into this as I'm at it.

I seem to have discovered an interesting phenomenon

Among the recommended open source projects, there seems to be some open source installation software on Android that is based on reading anime or comics. It seems to be a trend recently.


Okay, I won't bother you with your research

It's almost 2025 January, New Year's Day is coming soon

**Comment by OSNewbie** [comment]
#1477

**Pull request merged**
